### ISSUE TITLE
Spring Transaction Management not working with Spring Boot + MyBatis?

### ISSUE THREAD

**Issue by shouzheng** [mybatis/spring-boot-starter#156]
[Spring Transaction Management not working with Spring Boot + MyBatis?](http://stackoverflow.com/questions/37310550/spring-transaction-management-not-working-with-spring-boot-mybatis)

It's work on the class but not on the method.

**Comment by kazuki43zoo** [comment]
The Spring Transaction Management with Spring Boot + Mybatis is working fine.
If you think a bug, please provide more informations(detail conditions, expected behavior, actual behavior, minimum reproduce project ).

Note:
I've commented at http://stackoverflow.com/questions/37310550/spring-transaction-management-not-working-with-spring-boot-mybatis/43328596#43328596

I've closed this, but you can reopen if needed.
Also, if you have a question, please post [mailing list](minimum reproduce project) or [stackoverflow](https://stackoverflow.com/questions/ask?tags=mybatis) at next time.
