### ISSUE TITLE
Does @Mapper support a value attribute to specify the bean name?

### ISSUE THREAD

**Issue by nuttycat** [mybatis/spring-boot-starter#189]
When I have two dao with the same name in different package,I get a bean name conflict .
I can use the @Component annotation to specify the name to avoid this confict.
Could @Mapper annotation support  a value attribute  to specify the bean name in the future?

**Comment by kazuki43zoo** [comment]
Hi @nuttycat,  We have no plan to add the attribute that specifies the bean name because `@Mapper` has belonged in mybatis core module.

>  @component annotation to specify the name to avoid this confict.

I think this is work as the design for us.
If you need this feature strongly, I suggest creating an issue to the mybatis-spring project rather than this project.

Note:
By default, the mybatis generate a bean name using [`AnnotationBeanNameGenerator`](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/context/annotation/AnnotationBeanNameGenerator.html) provided by Spring.

**Comment by nuttycat** [comment]
Thanks,get a lot of ideas from this reply.
