### ISSUE TITLE
not support ZonedDateTime in 2.0.1

### ISSUE THREAD

**Issue by qlaall** [mybatis/spring-boot-starter#349]
i use org.mybatis.spring.boot.mybatis-spring-boot-starter 2.0.1 and org.postgresql.postgresql 42.2.5
it throw exception when i select a timestamptz field
"conversion to class java.time.ZonedDateTime from 93 not supported"

Return to normal after returning to version 1.3.2

```xml
       <!-- https://mvnrepository.com/artifact/org.mybatis.spring.boot/mybatis-spring-boot-starter -->
        <!--        <dependency>-->
        <!--            <groupId>org.mybatis.spring.boot</groupId>-->
        <!--            <artifactId>mybatis-spring-boot-starter</artifactId>-->
        <!--            <version>2.0.1</version>-->
        <!--        </dependency>-->
```
```java
@Table(name ="xxxx")
public class RUserEnsure {
    @Id
    @KeySql(useGeneratedKeys = true)
    @Column(name = "id", insertable = false)
    private Long id;
    private String userId;
    private String xxxx;
    @Column(insertable = false)
    private ZonedDateTime createTime; 

    // getter & setter
}
```

**Comment by harawata** [comment]
Hi @qlaall ,

As the error says, the driver does not support `ZonedDateTime`.
In fact, PostgreSQL does not store the time zone information (the data is stored in UTC), so it is not possible to save/retrieve `ZonedDateTime` correctly.
Have you considered using `LocalDateTime` instead?

The error occurs after upgraded to 2.0.1 because we changed the `ZonedDateTimeTypeHandler` implementation in MyBatis 3.5.0. Please see https://github.com/mybatis/mybatis-3/issues/1081 for details.
If the [old implementation](https://github.com/harawata/mybatis-3/blob/a2ef920a5fc58256d57968c69423c033bf6779d3/src/main/java/org/apache/ibatis/type/ZonedDateTimeTypeHandler.java) worked perfectly for you, it is possible to copy it as a custom type handler and register it globally in the config.

Please let me know if you need any further clarification.

**Comment by qlaall** [comment]
@harawata thanks ，I use ZonedDateTime just because I might receive data from different time zones, but I need a uniform way to save.
So ZonedDateTime allows me to avoid the time zone format of a database store in the document after manual processing. Timestamp is missing information for me. I also need to find the document to see if the program converts the read data into GMT+8 or GMT+0, this is a place that may cause ambiguity for me.


But it doesn't matter. The old version is valid for me.

**Comment by harawata** [comment]
Thanks for the reply, @qlaall !
I believe we can close this issue, then.

By the way, I forgot to mention that the driver supports `OffsetDateTime`.
So, if it meets your requirements, it could be a better choice.
