### ISSUE TITLE
how to spring boot multiple datasource java config for mybatis

### ISSUE THREAD

**Issue by tom0512** [mybatis/spring-boot-starter#380]
how to spring boot multiple datasource java config for mybatis

**Comment by kazuki43zoo** [comment]
@tom0512 

I've closed this issue because we manage only bug and feature request(includes improvement) on GitHub. Please post your question on [mailing list](https://groups.google.com/forum/#!forum/mybatis-user) or [stack overflow](https://stackoverflow.com/questions/tagged/mybatis) instead of.

p.s: 
The mybatis-spring-boot-starter does not support auto-configuration when  use multiple datasource. You should configure a `SqlSessionFactory` and `SqlSessionTemplate` provided by mybatis-spring by manually at your configuration class.
