### ISSUE TITLE
Problem using a Mockito mock on a MyBatis (Mapper annotated) interface.

### ISSUE THREAD

**Issue by dldiehl77** [mybatis/spring-boot-starter#475]
I am using MyBatis Spring Boot Starter version 2.1.3. Ever since moving to Spring Boot 2.2.7 (I've also tried 2.2.8 and 2.3.1 with the same results), I've had a problem using the MockBean annotation to mock a MyBatis interface (e.g. DAO or Mapper).

I have a MyBatis interface annotated with both Mapper and Repository.  When I try to use the Spring Boot MockBean annotation, the object that is injected into my Service classes and the object that is injected into my unit test class are not the same, making it so that I cannot use Mockito.verify (as an example of one issue this causes).

A complete description is on stackoverflow here:  https://stackoverflow.com/questions/62409666/mockbean-and-mybatis-mapper-not-working-together-as-they-did-before-spring-boot

Including a demo of the issue here:  github.com/dldiehl77/mybatis-issues/tree/master/so-62409666

**Comment by harawata** [comment]
Thank you very much, @dldiehl77 !

This is a side effect of the fix for https://github.com/spring-projects/spring-boot/issues/20665 .
The solution is to add `FactoryBean.OBJECT_TYPE_ATTRIBUTE` [1] attribute to mapper beans, it seems.

@kazuki43zoo ,
I opened a PR https://github.com/mybatis/spring/pull/494 on mybatis-spring, but does it make more sense to do it in mybatis-spring-boot-starter? (I wasn't sure if that's possible)

Thanks in advance!

[1] https://github.com/spring-projects/spring-boot/commit/f4985abf3cd299f0842d9f474942c418f177eb13

**Comment by harawata** [comment]
Hello @dldiehl77 !

We have merged https://github.com/mybatis/spring/pull/494 .
You should be able to verify the fix using the latest 2.1.4-SNAPSHOT.
Thank you again for your contribution!
