### ISSUE TITLE
Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required

### ISSUE THREAD

**Issue by xuezhongliang** [mybatis/spring-boot-starter#631]
I use mybatis-spring-boot-starter:2.1.+ version, then run the test case , show the wrong info : Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required, the new version change the usage???

**Comment by kazuki43zoo** [comment]
@xuezhongliang Sorry, late reply. Cloud you provide small repro project?

**Comment by WatcherOne** [comment]
@xuezhongliang you sure that version is 2.1.+ ； I use mybatis-spring-boot-starter:2.1.3 version，it's ok；but，use 3.0.0 ，show same error info

**Comment by sialais** [comment]
I've meet the same problem.
I found it caused by this commit: [Drop EnableAutoConfiguration from spring.factories](https://github.com/mybatis/spring-boot-starter/pull/755/commits/83bbac7a09a4990607d0e86c89f5db2c13b31316)
The auto config class `MybatisAutoConfiguration` not loaded, adding `@ImportAutoConfiguration(MybatisAutoConfiguration.class)` for temporary fix.

**Comment by kazuki43zoo** [comment]
@xuezhongliang 
Close this issue because no reply at long time. You can reopen this issue if you cannot resolve yet. Thanks!
