### ISSUE TITLE
how can support spring boot 3.0

### ISSUE THREAD

**Issue by lin3fei** [mybatis/spring-boot-starter#697]
i created spring boot 3.0.0_m4, and incloud mybatis-spring 2.2.x, but it can not start, and error  create sqlsessionfactory bean error, could you help me? thanks

**Comment by SunGungg** [comment]
i have the same error. the reason is Latest spring-framework removed NestedIOException. you can copy this class from older jar.
and you can start up.
see my issue, maybe for help https://github.com/mybatis/spring-boot-starter/issues/691

**Comment by hazendaz** [comment]
well... probably no surprise here but we haven't released support for jakarta yet.  I think you will find that is the case with most downstream repos as core products that are highly used like spring have to get their first.  Since spring doesn't publish work in progress into maven central, it does make it a bit more complicated. I know some work was being done in this area along with other parts of mybatis projects to support jakarta but nothing is officially out or anything at this point in time.

**Comment by kazuki43zoo** [comment]
We will support spring boot 3 (spring-framework 6) on 2.3.0 (now only release snapshot version to Sonatype OSS repository). Please use mybatis-spring-boot 2.3.0-SNAPSHOT.

**Comment by lin3fei** [comment]
Thanks @kazuki43zoo ,
