### ISSUE TITLE
mybatis-spring jar is published in maven central repo?

### ISSUE THREAD

**Issue by agongi** [mybatis/spring-boot-starter#775]
Hello, Im facing problem to apply mybatis-spring to 2.3.x from 2.1.x.
but there is no deployed jar but found in releases/tags

- version compatibility
<img width="1059" alt="Screenshot 2022-12-14 at 16 33 28" src="https://user-images.githubusercontent.com/5780627/207533479-433b21b1-58b3-4ec8-81fd-2b7b644f9e52.png">

- mvn central
<img width="874" alt="Screenshot 2022-12-14 at 16 33 34" src="https://user-images.githubusercontent.com/5780627/207533519-7119aa05-613b-4a06-950a-d92c67b211ea.png">

is it intended not to support 2.3.x in public? (means 2.1.0 or 3.0.x are only recommended)

**Comment by hazendaz** [comment]
Spring boot starter is a separate versioned product the mapping is showing what needs to match between the two.  So mybatis spring 2.1.0 if using spring boot goes with starter 2.3.0.

All current tagged releases are out both in tagging the releases on github with release drafted as well as in central.  The only non released at the moment as compared to commits is the boot starter 3.0.1 which is in progress due to javadoc issues but will be out this weekend.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Suktae Choi ***@***.***>
Sent: Wednesday, December 14, 2022 2:36:04 AM
To: mybatis/spring-boot-starter ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mybatis/spring-boot-starter] mybatis-spring jar is published in maven central repo? (Issue #775)


Hello, Im facing problem to apply mybatis-spring to 2.3.x from 2.1.x.
but there is no deployed jar but found in releases/tags

  *   version compatibility

[Screenshot 2022-12-14 at 16 33 28]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F5780627%2F207533479-433b21b1-58b3-4ec8-81fd-2b7b644f9e52.png&data=05%7C01%7C%7C14d0ca7b83ca4f42294c08dadda5db62%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638066001669170409%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0TcOeg4o%2F78OtjXYw05Pna4fuxYkL6s1hxvIDLkLRfo%3D&reserved=0>

  *   mvn central

[Screenshot 2022-12-14 at 16 33 34]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F5780627%2F207533519-7119aa05-613b-4a06-950a-d92c67b211ea.png&data=05%7C01%7C%7C14d0ca7b83ca4f42294c08dadda5db62%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638066001669170409%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TzSAhXDfCcYxMrzY1%2FNAheda%2BIF3Kb9PsaIHFA0Ehi8%3D&reserved=0>

is it intended not to support 2.3.x in public? (means 2.1.0 or 3.0.x are only recommended)

**Comment by agongi** [comment]
👍 thank you for answering
