### ISSUE TITLE
Lazy Loading

### ISSUE THREAD

**Issue by oleg172** [mybatis/spring-boot-starter#790]
I'am using mybatis-spring-boot-starter, version = 2.3.0.
I Have data source config like this:
```
@Configuration
@MapperScan(basePackages = "com.services.dbframeworkpilot.dao.mapper", annotationClass = FnsDataSource.class, sqlSessionFactoryRef = FnsDataSourceConfig.SQL_SESSION_FACTORY_NAME)
public class FnsDataSourceConfig {
    public static final String SQL_SESSION_FACTORY_NAME = "fnsSF";

    @Bean(name = "fnsDS")
    @ConfigurationProperties("db.datasource")
    public DataSource dataSource() {
        return DataSourceBuilder.create().build();
    }

    @Bean(name = "fnsTM")
    public PlatformTransactionManager txManagerKm() {
        return new DataSourceTransactionManager(dataSource());
    }

    @Bean(name = SQL_SESSION_FACTORY_NAME)
    public SqlSessionFactory sqlSessionFactoryBean() throws Exception {
        SqlSessionFactoryBean sqlSessionFactoryBean = new SqlSessionFactoryBean();
        sqlSessionFactoryBean.setDataSource(dataSource());
        org.apache.ibatis.session.Configuration configuration = new org.apache.ibatis.session.Configuration();
        configuration.getLazyLoadTriggerMethods().clear();
        configuration.setMapUnderscoreToCamelCase(true);
        configuration.setLazyLoadingEnabled(true);
        configuration.setAggressiveLazyLoading(false);
        sqlSessionFactoryBean.setConfiguration(configuration);
        return sqlSessionFactoryBean.getObject();
    }
}
```
Mapper:
```
@Mapper
@FnsDataSource
public interface BookingMapper {

    @Results(value = {
            @Result(property = "id", column = "book_id"),
            @Result(property = "bookDate", column = "book_date"),
            @Result(property = "totalAmount", column = "total_amount"),
            @Result(property = "tickets", javaType = List.class, column = "book_id",
                    many = @Many(select = "ru.rencredit.services.dbframeworkpilot.dao.mapper.TicketMapper.getTicketsByBookId", fetchType = FetchType.LAZY))
    })
    @Select(value = "SELECT * FROM BOOKINGS WHERE BOOK_ID = #{id}")
    Booking getBookingById(@Param("id") String id);
}
```
DTO class:
```
@javax.annotation.Generated(value = "com.services.swagger.RenCreditCodegen", date = "2023-02-08T10:11:57.991+03:00")
@Accessors(chain = true)
@NoArgsConstructor
@EqualsAndHashCode
public class Booking {
    private String id;
    private ZonedDateTime bookDate;
    private BigDecimal totalAmount;
    private List<Ticket> tickets;

    public String getId() {
        return id;
    }

    public ZonedDateTime getBookDate() {
        return bookDate;
    }

    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    public List<Ticket> getTickets() {
        return tickets;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setBookDate(ZonedDateTime bookDate) {
        this.bookDate = bookDate;
    }

    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    public void setTickets(List<Ticket> tickets) {
        this.tickets = tickets;
    }

    public void addTicketsItem(Ticket ticketsItem) {
        if (this.tickets == null) {
            this.tickets = new ArrayList<>();
        }
        this.tickets.add(ticketsItem);
    }
}
```
When I try to call mapper to get bookings - I expect that 'tickets' willn't call immediately, because in SqlSessionFactory bean I enabled LazyLoading and cleared all LazyLoadTriggerMethods. If in DTO class I delete annotation '@EqualsAndHashCode' - it is work as I expect. 
How I should configure application to enable lazy loading for DTOs with annotation '@EqualsAndHashCode'?

**Comment by hazendaz** [comment]
What is your actual error?  That annotation is for lombok and is a compile time only annotation.  I'm failing to see the relationship to a mybatis issue without more details.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: oleg172 ***@***.***>
Sent: Wednesday, February 8, 2023 4:40:11 AM
To: mybatis/spring-boot-starter ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mybatis/spring-boot-starter] Lazy Loading (Issue #790)


I'am using mybatis-spring-boot-starter, version = 2.3.0.
I Have data source config like this:
***@***.***
@MapperScan(basePackages = "com.services.dbframeworkpilot.dao.mapper", annotationClass = FnsDataSource.class, sqlSessionFactoryRef = FnsDataSourceConfig.SQL_SESSION_FACTORY_NAME)
public class FnsDataSourceConfig {
public static final String SQL_SESSION_FACTORY_NAME = "fnsSF";

@Bean(name = "fnsDS")
@ConfigurationProperties("db.datasource")
public DataSource dataSource() {
    return DataSourceBuilder.create().build();
}

@Bean(name = "fnsTM")
public PlatformTransactionManager txManagerKm() {
    return new DataSourceTransactionManager(dataSource());
}

@Bean(name = SQL_SESSION_FACTORY_NAME)
public SqlSessionFactory sqlSessionFactoryBean() throws Exception {
    SqlSessionFactoryBean sqlSessionFactoryBean = new SqlSessionFactoryBean();
    sqlSessionFactoryBean.setDataSource(dataSource());
    org.apache.ibatis.session.Configuration configuration = new org.apache.ibatis.session.Configuration();
    configuration.getLazyLoadTriggerMethods().clear();
    configuration.setMapUnderscoreToCamelCase(true);
    configuration.setLazyLoadingEnabled(true);
    configuration.setAggressiveLazyLoading(false);
    sqlSessionFactoryBean.setConfiguration(configuration);
    return sqlSessionFactoryBean.getObject();
}


***@***.***<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMapper&data=05%7C01%7C%7C428fd377193f4d25595f08db09b879ba%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638114460142968652%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vkma9xDClEeV2U1TQuKBR09IiA4zE2uv%2FhXxHwv8bjY%3D&reserved=0>
@FnsDataSource
public interface BookingMapper {

@Results(value = {
        @Result(property = "id", column = "book_id"),
        @Result(property = "bookDate", column = "book_date"),
        @Result(property = "totalAmount", column = "total_amount"),
        @Result(property = "tickets", javaType = List.class, column = "book_id",
                many = @Many(select = "ru.rencredit.services.dbframeworkpilot.dao.mapper.TicketMapper.getTicketsByBookId", fetchType = FetchType.LAZY))
})
@Select(value = "SELECT * FROM BOOKINGS WHERE BOOK_ID = #{id}")
Booking ***@***.***("id") String id);


}DTO ***@***.***(value = "ru.rencredit.services.swagger.RenCreditCodegen", date = "2023-02-08T10:11:57.991+03:00")
@accessors<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faccessors&data=05%7C01%7C%7C428fd377193f4d25595f08db09b879ba%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638114460142968652%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=O5U81YCm43eDW0Gow188s3CFYA5%2BJi5lBpXnxy4IMUM%3D&reserved=0>(chain = true)
@NoArgsConstructor<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNoArgsConstructor&data=05%7C01%7C%7C428fd377193f4d25595f08db09b879ba%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638114460142968652%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TsanuvuPnrESoVRCzauzk9sDItuAfrNdHgSriPDFvZM%3D&reserved=0>
@EqualsAndHashCode<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEqualsAndHashCode&data=05%7C01%7C%7C428fd377193f4d25595f08db09b879ba%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638114460142968652%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=52Jy2Frp8yc6arEYeL19w8zeJQt2Zd2qod8uC5%2BIMCo%3D&reserved=0>
public class Booking {
private String id;
private ZonedDateTime bookDate;
private BigDecimal totalAmount;
private List tickets;

public String getId() {
    return id;
}

public ZonedDateTime getBookDate() {
    return bookDate;
}

public BigDecimal getTotalAmount() {
    return totalAmount;
}

public List<Ticket> getTickets() {
    return tickets;
}

public void setId(String id) {
    this.id = id;
}

public void setBookDate(ZonedDateTime bookDate) {
    this.bookDate = bookDate;
}

public void setTotalAmount(BigDecimal totalAmount) {
    this.totalAmount = totalAmount;
}

public void setTickets(List<Ticket> tickets) {
    this.tickets = tickets;
}

public void addTicketsItem(Ticket ticketsItem) {
    if (this.tickets == null) {
        this.tickets = new ArrayList<>();
    }
    this.tickets.add(ticketsItem);
}


}`
When I try to call mapper to get bookings - I expect that 'tickets' willn't call immediately, because in SqlSessionFactory bean I enabled LazyLoading and cleared all LazyLoadTriggerMethods. If in DTO class I delete annotation ***@***.***<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEqualsAndHashCode&data=05%7C01%7C%7C428fd377193f4d25595f08db09b879ba%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638114460142968652%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=52Jy2Frp8yc6arEYeL19w8zeJQt2Zd2qod8uC5%2BIMCo%3D&reserved=0>' - it is work as I expect.
How I should configure application to enable lazy loading for DTOs with annotation ***@***.***<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEqualsAndHashCode&data=05%7C01%7C%7C428fd377193f4d25595f08db09b879ba%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638114460142968652%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=52Jy2Frp8yc6arEYeL19w8zeJQt2Zd2qod8uC5%2BIMCo%3D&reserved=0>'?

**Comment by oleg172** [comment]
@hazendaz, when I call mapper method, 'tickets' is loaded immedaitely:
```
Booking booking = bookingDAO.getBookingById(bookingId);
```

But in mapper for column 'tickets' I had fetchType = LAZY. Why does tickets loaded immediately? I expect that 'tickets' should load only when I call get method for 'tickets':

```
booking.getTickets();
 ```

**Comment by harawata** [comment]
Hello @oleg172 ,

If you could provide a small repro project like [these](https://github.com/harawata/mybatis-issues), we may be able to explain what is happening, at least.

**Comment by andreika63** [comment]
Hello @oleg172 ,
@EqualsAndHashCode means that all filelds will be used to compute equals (try to use delombok ide feature to view result class). So getters fired. Try to use @EqualsAndHashCode(of = "id")

**Comment by oleg172** [comment]
Hello @andreika63.
I thought if I clear LazyLoadTriggerMethods, equals and hashcode shoudn't trigger loading of lazy data. I was wrong? If we have equals or hashcode, which using lazy data - data will loadinf automatically?

**Comment by andreika63** [comment]
Hello @oleg172 , just try to find out code where configuration param is used, use debug.
I've found code:
if (aggressive || lazyLoadTriggerMethods.contains(methodName)) {
   lazyLoader.loadAll();
   ............

**Comment by kazuki43zoo** [comment]
@oleg172 If you could provide a small repro project?
