### ISSUE TITLE
Update to MyBatis 3.4.2 and MyBatis-Spring 1.3.1

### ISSUE THREAD

**Issue by blmarket** [mybatis/spring-boot-starter#81]
current latest release 1.1.1 contains only 3.4.0, which is not the latest one.

**Comment by kazuki43zoo** [comment]
This issue fix via #79. 3.4.1 will include in 1.1.2.
However, 1.1.2 has not been released yet.

**Comment by mallim** [comment]
any particular date version 1.1.2 will be release ?

**Comment by kopax** [comment]
I am struggling on internet trying to find a non deprecated tutorial for making it work (eg: use multiple .properties instead of .yml, different sql jdbc drivers ...)
I have this dependencies in my gradle

    compile("org.mybatis:mybatis:3.4.1")
    compile("org.mybatis:mybatis-spring:1.3.0")
    compile("org.springframework.boot:spring-boot-starter-web") 

I use the latest version of MariaDB, spring-boot, mybatis. 
As noticed by @blmarket and @mallim , the mybatis/spring-boot-starter seems outdated.
Can anyone confirm me that I should downgrade before trying anything ? Or can I use the latest version of each framework ? Should I use official mariadb driver ? They are more up to date than the mysql one? Or should I just use the included mysql driver offered in the springframework package ?

**Comment by kazuki43zoo** [comment]
@eddumelendez 

I hope to release 1.2.0 after release MyBatis 3.4.2.

**Comment by eddumelendez** [comment]
@kazuki43zoo we will include mybatis 3.4.2 and I'll request the release of the next version. Thanks to be worried about the project. 👍

**Comment by softboy99** [comment]
I'm also waiting for that update, Thanks.

**Comment by kopax** [comment]
FYI, there is an amazing plugin that has just been release this month for spring and mybatis.

It work with [spring-data](http://projects.spring.io/spring-data/), [spring-data-rest](http://projects.spring.io/spring-data-rest/), [spring-hateoas](http://projects.spring.io/spring-hateoas/).

The project : https://github.com/hatunet/spring-data-mybatis/

If you want to test it out with me, the author has just finished it and took care of the few issues it had on it's firsts versions.

**Comment by kazuki43zoo** [comment]
I've updated to MyBatis 3.4.2 and MyBatis-Spring 1.3.1.
And I've fixed assertion error for configuration properties.
