### ISSUE TITLE
Plans to support Spring Boot 3.3.0?

### ISSUE THREAD

**Issue by mhalbritter** [mybatis/spring-boot-starter#979]
Hello,

Spring Boot 3.3.0 has been released, however, the latest release of this starter has been built against Boot 3.2.0. Are there plans to build and test against Boot 3.3.0?

As of now, MyBatis is not selectable with Boot 3.3.0 on start.spring.io:

![image](https://github.com/mybatis/spring-boot-starter/assets/98899556/9ef6bc15-bc8d-40a5-bd3c-3fd86d1ca4c8)

**Comment by harawata** [comment]
Thanks for the heads up, @mhalbritter .

I have submitted a PR : https://github.com/spring-io/start.spring.io/pull/1511
Subscribe the PR to follow the progress.

**Comment by hazendaz** [comment]
Just to add here, we need to adjust our byte code enforcer.  I believe we are fine with 3.3.0.  But not certain as builds fail because tomcat uses ant and IMO missed the mark on how to do multi jars but I haven't directly confirmed other than allowing Catalina to violate everywhere for now.

I'll try to fix this up here tonight and kick a release if it's all good in case that matters on the other part.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
